---
###api gateway config file
#route map mysql config table
db:
  host: "apigatewayqa7:apigatewayqa7@tcp(vpc-qa-new.cmcopvs0wxn0.rds.cn-north-1.amazonaws.com.cn:3306)/apigatewayqa7?charset=utf8"

#redis for auth
redis:
  host: "127.0.0.1:6379"
  pwd: ""
  db: 9

#debug and metrics addr
debug: ":18081"

#admin manager tools
admin: ":18082"

#proxy addr
proxy: ":8083"

#https addr
https:
  addr: "18088"
  enable: false
  cert: "./ssl-cert-snakeoil.pem"
  key: "./ssl-cert-snakeoil.key"

#etcd addrs
etcd:
- "http://127.0.0.1:2379"

#log file
log:
  dir: "/tmp/apigateway"

#针对ip限制策略
limit:
  #每n ms
  ttl: 1000
  #允许请求数
  max: 5
