---
###job-schedule config file
#try max times
times: 50
#jobs
jobs:
- description: "product price redis"
  cmd: "/usr/bin/php"
  params: "/opt/www/meme-product/application/cronds/PriceRedisReceiver.php"
  max: 1
