<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *return userinfo
 * </pre>
 *
 * Protobuf type <code>pb.GetUserinfoResponse</code>
 */
class GetUserinfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.pb.Userinfo userinfo = 1;</code>
     */
    private $userinfo = null;
    /**
     * <code>string err = 2;</code>
     */
    private $err = '';

    public function __construct() {
        \GPBMetadata\Svc::initOnce();
        parent::__construct();
    }

    /**
     * <code>.pb.Userinfo userinfo = 1;</code>
     */
    public function getUserinfo()
    {
        return $this->userinfo;
    }

    /**
     * <code>.pb.Userinfo userinfo = 1;</code>
     */
    public function setUserinfo(&$var)
    {
        GPBUtil::checkMessage($var, \Pb\Userinfo::class);
        $this->userinfo = $var;
    }

    /**
     * <code>string err = 2;</code>
     */
    public function getErr()
    {
        return $this->err;
    }

    /**
     * <code>string err = 2;</code>
     */
    public function setErr($var)
    {
        GPBUtil::checkString($var, True);
        $this->err = $var;
    }

}

