<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *get userinfo by id
 * </pre>
 *
 * Protobuf type <code>pb.GetUserinfoRequest</code>
 */
class GetUserinfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 id = 1;</code>
     */
    private $id = 0;

    public function __construct() {
        \GPBMetadata\Svc::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;
    }

}

