<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svc.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *userinfo definition
 * </pre>
 *
 * Protobuf type <code>pb.Userinfo</code>
 */
class Userinfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <code>string username = 2;</code>
     */
    private $username = '';
    /**
     * <code>string phone = 3;</code>
     */
    private $phone = '';
    /**
     * <code>int64 sex = 4;</code>
     */
    private $sex = 0;
    /**
     * <code>string avatar = 5;</code>
     */
    private $avatar = '';
    /**
     * <code>int64 gouhao = 6;</code>
     */
    private $gouhao = 0;
    /**
     * <code>int64 birthday = 7;</code>
     */
    private $birthday = 0;
    /**
     * <code>string avatars = 8;</code>
     */
    private $avatars = '';
    /**
     * <code>string signature = 9;</code>
     */
    private $signature = '';
    /**
     * <code>string appfrom = 10;</code>
     */
    private $appfrom = '';
    /**
     * <code>string appver = 11;</code>
     */
    private $appver = '';
    /**
     * <code>string backgroud_image = 12;</code>
     */
    private $backgroud_image = '';
    /**
     * <code>string update_appver = 13;</code>
     */
    private $update_appver = '';
    /**
     * <code>int64 privacy = 14;</code>
     */
    private $privacy = 0;
    /**
     * <code>int64 loadRecTags = 15;</code>
     */
    private $loadRecTags = 0;
    /**
     * <code>int64 game_power = 16;</code>
     */
    private $game_power = 0;
    /**
     * <code>int64 mark = 17;</code>
     */
    private $mark = 0;
    /**
     * <code>int64 level = 18;</code>
     */
    private $level = 0;
    /**
     * <code>string question_photo = 19;</code>
     */
    private $question_photo = '';
    /**
     * <code>string lan = 20;</code>
     */
    private $lan = '';
    /**
     * <code>int64 notify = 21;</code>
     */
    private $notify = 0;
    /**
     * <code>repeated int64 bindGameIds = 22;</code>
     */
    private $bindGameIds;
    /**
     * <code>string userPosition = 23;</code>
     */
    private $userPosition = '';
    /**
     * <code>int64 userStatus = 24;</code>
     */
    private $userStatus = 0;
    /**
     * <code>string imToken = 25;</code>
     */
    private $imToken = '';

    public function __construct() {
        \GPBMetadata\Svc::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>int64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;
    }

    /**
     * <code>string username = 2;</code>
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * <code>string username = 2;</code>
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;
    }

    /**
     * <code>string phone = 3;</code>
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * <code>string phone = 3;</code>
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;
    }

    /**
     * <code>int64 sex = 4;</code>
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * <code>int64 sex = 4;</code>
     */
    public function setSex($var)
    {
        GPBUtil::checkInt64($var);
        $this->sex = $var;
    }

    /**
     * <code>string avatar = 5;</code>
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * <code>string avatar = 5;</code>
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;
    }

    /**
     * <code>int64 gouhao = 6;</code>
     */
    public function getGouhao()
    {
        return $this->gouhao;
    }

    /**
     * <code>int64 gouhao = 6;</code>
     */
    public function setGouhao($var)
    {
        GPBUtil::checkInt64($var);
        $this->gouhao = $var;
    }

    /**
     * <code>int64 birthday = 7;</code>
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * <code>int64 birthday = 7;</code>
     */
    public function setBirthday($var)
    {
        GPBUtil::checkInt64($var);
        $this->birthday = $var;
    }

    /**
     * <code>string avatars = 8;</code>
     */
    public function getAvatars()
    {
        return $this->avatars;
    }

    /**
     * <code>string avatars = 8;</code>
     */
    public function setAvatars($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatars = $var;
    }

    /**
     * <code>string signature = 9;</code>
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * <code>string signature = 9;</code>
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, True);
        $this->signature = $var;
    }

    /**
     * <code>string appfrom = 10;</code>
     */
    public function getAppfrom()
    {
        return $this->appfrom;
    }

    /**
     * <code>string appfrom = 10;</code>
     */
    public function setAppfrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->appfrom = $var;
    }

    /**
     * <code>string appver = 11;</code>
     */
    public function getAppver()
    {
        return $this->appver;
    }

    /**
     * <code>string appver = 11;</code>
     */
    public function setAppver($var)
    {
        GPBUtil::checkString($var, True);
        $this->appver = $var;
    }

    /**
     * <code>string backgroud_image = 12;</code>
     */
    public function getBackgroudImage()
    {
        return $this->backgroud_image;
    }

    /**
     * <code>string backgroud_image = 12;</code>
     */
    public function setBackgroudImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->backgroud_image = $var;
    }

    /**
     * <code>string update_appver = 13;</code>
     */
    public function getUpdateAppver()
    {
        return $this->update_appver;
    }

    /**
     * <code>string update_appver = 13;</code>
     */
    public function setUpdateAppver($var)
    {
        GPBUtil::checkString($var, True);
        $this->update_appver = $var;
    }

    /**
     * <code>int64 privacy = 14;</code>
     */
    public function getPrivacy()
    {
        return $this->privacy;
    }

    /**
     * <code>int64 privacy = 14;</code>
     */
    public function setPrivacy($var)
    {
        GPBUtil::checkInt64($var);
        $this->privacy = $var;
    }

    /**
     * <code>int64 loadRecTags = 15;</code>
     */
    public function getLoadRecTags()
    {
        return $this->loadRecTags;
    }

    /**
     * <code>int64 loadRecTags = 15;</code>
     */
    public function setLoadRecTags($var)
    {
        GPBUtil::checkInt64($var);
        $this->loadRecTags = $var;
    }

    /**
     * <code>int64 game_power = 16;</code>
     */
    public function getGamePower()
    {
        return $this->game_power;
    }

    /**
     * <code>int64 game_power = 16;</code>
     */
    public function setGamePower($var)
    {
        GPBUtil::checkInt64($var);
        $this->game_power = $var;
    }

    /**
     * <code>int64 mark = 17;</code>
     */
    public function getMark()
    {
        return $this->mark;
    }

    /**
     * <code>int64 mark = 17;</code>
     */
    public function setMark($var)
    {
        GPBUtil::checkInt64($var);
        $this->mark = $var;
    }

    /**
     * <code>int64 level = 18;</code>
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * <code>int64 level = 18;</code>
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->level = $var;
    }

    /**
     * <code>string question_photo = 19;</code>
     */
    public function getQuestionPhoto()
    {
        return $this->question_photo;
    }

    /**
     * <code>string question_photo = 19;</code>
     */
    public function setQuestionPhoto($var)
    {
        GPBUtil::checkString($var, True);
        $this->question_photo = $var;
    }

    /**
     * <code>string lan = 20;</code>
     */
    public function getLan()
    {
        return $this->lan;
    }

    /**
     * <code>string lan = 20;</code>
     */
    public function setLan($var)
    {
        GPBUtil::checkString($var, True);
        $this->lan = $var;
    }

    /**
     * <code>int64 notify = 21;</code>
     */
    public function getNotify()
    {
        return $this->notify;
    }

    /**
     * <code>int64 notify = 21;</code>
     */
    public function setNotify($var)
    {
        GPBUtil::checkInt64($var);
        $this->notify = $var;
    }

    /**
     * <code>repeated int64 bindGameIds = 22;</code>
     */
    public function getBindGameIds()
    {
        return $this->bindGameIds;
    }

    /**
     * <code>repeated int64 bindGameIds = 22;</code>
     */
    public function setBindGameIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->bindGameIds = $var;
    }

    /**
     * <code>string userPosition = 23;</code>
     */
    public function getUserPosition()
    {
        return $this->userPosition;
    }

    /**
     * <code>string userPosition = 23;</code>
     */
    public function setUserPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->userPosition = $var;
    }

    /**
     * <code>int64 userStatus = 24;</code>
     */
    public function getUserStatus()
    {
        return $this->userStatus;
    }

    /**
     * <code>int64 userStatus = 24;</code>
     */
    public function setUserStatus($var)
    {
        GPBUtil::checkInt64($var);
        $this->userStatus = $var;
    }

    /**
     * <code>string imToken = 25;</code>
     */
    public function getImToken()
    {
        return $this->imToken;
    }

    /**
     * <code>string imToken = 25;</code>
     */
    public function setImToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->imToken = $var;
    }

}

